I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 718, in script
    t "Oh~ Nate how are you today?~"
Exception: Sayer 't' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 718, in script
    t "Oh~ Nate how are you today?~"
  File "C:\Users\BowTi\Documents\renpy-6.99.13-sdk\renpy\ast.py", line 596, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\BowTi\Documents\renpy-6.99.13-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 't' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Dragon Wolf 1.0
